spring.application.name=user-service
server.port=8081
server.address=0.0.0.0

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.datasource.url=jdbc:mariadb://54.210.117.152:3306/PingMe_DB
spring.datasource.username=admin
spring.datasource.password=i92fuoizsvdsdryn
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

secrete.key=YmFzaWN0ZWxsbnVtZXJhbGNhcmVmdWxzdG9yZXByb2dyZXNzcm9hZG5ldmVycGFydHk=